/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sn.isi.swing;

import java.sql.ResultSet;
import java.util.ArrayList;
import sn.isi.entities.Client;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sn.isi.dao.DB;

/**
 *
 * @author khadi
 */
public class ListeClient extends javax.swing.JFrame {

    private List<Client> list;
    private DefaultTableModel tab;

    /**
     * Creates new form ListeClient
     */
    public ListeClient() {

        initComponents();
        try {
            DB db = new DB();
            //creation de la liste des clients
            this.list = new ArrayList<Client>();
            db.open();
            String sql = "SELECT * FROM client";
            db.init(sql);
            ResultSet rset = db.executeSelect();
            while (rset.next()) {
                Client c = new Client();
                c.setId(rset.getInt(1));
                c.setPrenom(rset.getString(2));
                c.setNom(rset.getString(3));
                c.setEmail(rset.getString(4));
                c.setTel(rset.getString(5));
                //ajout des clients de la bdd dans notre liste
                list.add(c);
            }
            //creation d'un tableau local
            this.tab = new DefaultTableModel();
            this.tab.addColumn("#");
            this.tab.addColumn("Prenom");
            this.tab.addColumn("Nom");
            this.tab.addColumn("Email");
            this.tab.addColumn("tel");

            for (Client client : list) {
                this.tab.addRow(new Object[]{client.getId(), client.getPrenom(), client.getNom(), client.getEmail(), client.getTel()});
            }
            //affectation du tableau au tableau de notre interface
            this.tabClient.setModel(tab);
        } catch (Exception e) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabClient = new javax.swing.JTable();
        jLabel46 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));

        tabClient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tabClient.setForeground(new java.awt.Color(0, 153, 153));
        tabClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Prenom", "Nom", "Email", "Tel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabClient);

        jLabel46.setFont(new java.awt.Font("Cooper Black", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Liste des clients");

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("←");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        supprimer.setBackground(new java.awt.Color(204, 0, 0));
        supprimer.setForeground(new java.awt.Color(255, 255, 255));
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel46)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(supprimer))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jLabel46))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supprimer)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Accueil a = new Accueil();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:

        int selectedRow = tabClient.getSelectedRow();
        //recuperation de l'id
        String vid = tabClient.getValueAt(selectedRow, 0).toString();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(rootPane, "Veuillez selectionner une ligne");
        } else {
            int choix = JOptionPane.showConfirmDialog(rootPane,
                    "voulez supprimer le client",
                    "Confirmation",
                    JOptionPane.YES_NO_OPTION);
            if (choix == JOptionPane.YES_OPTION) {
                //recuperation de la ligne a supprime
                this.tab.removeRow(selectedRow);
                //recherche de l'id dans la base
                for (Client client : list) {

                    int idC = client.getId();
                    try {
                        int id = Integer.parseInt(vid);
                        //comparaison de l'id du tableau avec celui de la bdd
                        if (id == idC) {
                            //suppression du client dans le tableau
                            JOptionPane.showMessageDialog(rootPane, "nom : '" + client.getNom() + "'<br>email : '" + client.getEmail() + "'");

                            DB db = new DB();
                            //suppression du client dans la bdd
                            db.open();
                            String sql = "DELETE FROM client WHERE id = ?";
                            db.init(sql);
                            db.getPstm().setInt(1, id);
                            db.executeUpdate();
                            list.remove(client);
                        }
                    } catch (Exception e) {

                    }
                }

            }
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void tabClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClientMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_tabClientMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tabClient;
    // End of variables declaration//GEN-END:variables
}
